# Generated by Django 5.0.3 on 2024-03-15 11:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    """
    Represents a database migration.

    This class is responsible for defining the initial state of the database schema
    and the operations required to migrate the schema to a new version.
    """

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('image', models.ImageField(default='category_images/default.jpg', upload_to='category_images')),
            ],
        ),
        migrations.CreateModel(
            name='ProductVariant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sku', models.CharField(max_length=200)),
                ('name', models.CharField(max_length=200)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('details', models.CharField(max_length=200)),
                ('product_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bulk_insert.product')),
            ],
        ),
    ]
