# Generated by Django 5.0.3 on 2024-03-17 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bulk_insert', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(default='./static/category_images/default.jpg', upload_to='static/category_images'),
        ),
    ]
